# Pandas Foundations Practice

이번에는 새로운 작은 상품 데이터를 사용합니다. 설명을 다시 읽기보다, 앞에서 배운 방법을 스스로 꺼내 사용해보세요.

## 진행 방법

1. 문제를 읽고 필요한 열을 찾습니다.
2. 먼저 스스로 시도합니다.
3. 막히면 힌트를 한 단계씩 확인합니다.
4. 실행 결과를 기록합니다.

In [3]:
import pandas as pd

## 파일 불러오기

`data/products_basic.csv`를 읽어 `products`에 저장해보세요.

In [5]:
# CSV를 읽어 products 변수에 저장하세요. 파일 경로는 "data/products_basic.csv"입니다.
pass
products = pd.read_csv('data/products_basic.csv')

In [ ]:
##구글 코랩의 경우 
import os
os.makedirs('data', exist_ok=True)

from google.colab import files
uploaded = files.upload()   # 파일 선택창이 뜹니다

# 업로드된 파일을 data/ 로 옮기기
for name in uploaded:
    os.rename(name, f'data/{name}')

print(os.listdir('data'))

<details>
<summary>힌트 보기</summary>

`pd.read_csv("파일경로")` 형태를 떠올려보세요.

</details>

In [6]:
products = pd.read_csv("data/products_basic.csv")

# Mission 1 — 데이터부터 확인하기

아직 분석하지 마세요. 먼저 이 데이터 자체를 파악합니다.

In [214]:
# 데이터의 처음 몇 행을 확인하세요.
pass
type(products), products.shape, products.head(5), products.columns

(pandas.DataFrame,
 (13, 6),
     product category  price  stock  rating  low_stock
 0    무선 마우스     전자기기  28000     18     4.3      False
 1   기계식 키보드     전자기기  89000      7     4.7       True
 2    USB 허브     전자기기  35000     15     4.1      False
 3  블루투스 스피커     전자기기  52000      9     4.5       True
 4        노트       문구   4500     42     4.5      False,
 Index(['product', 'category', 'price', 'stock', 'rating', 'low_stock'], dtype='str'))

In [22]:
# 데이터가 몇 행 몇 열인지 확인하세요.
pass
products.head(10)

    product category  price  stock  rating
0    무선 마우스     전자기기  28000     18     4.3
1   기계식 키보드     전자기기  89000      7     4.7
2    USB 허브     전자기기  35000     15     4.1
3  블루투스 스피커     전자기기  52000      9     4.5
4        노트       문구   4500     42     4.5
5       플래너       문구  12000     25     4.0
6    형광펜 세트       문구   6500     33     3.8
7       텀블러       생활  22000     12     4.6
8    데스크 램프       생활  39000     10     4.2
9       정리함       생활  19000     20     3.9

In [23]:
products.tail(2)

   product category  price  stock  rating
11      후드       패션  69000      6     4.8
12     토트백       패션  32000     16     4.1

In [217]:
# 어떤 열들이 있는지 확인하세요.
pass
products.columns
prd_list = list(products.columns)
print(prd_list)

['product', 'category', 'price', 'stock', 'rating', 'low_stock']

In [18]:
# 각 열의 데이터 타입을 확인하세요.
pass
products.dtypes

product         str
category        str
price         int64
stock         int64
rating      float64
dtype: object

<details>
<summary>힌트 보기</summary>

처음 몇 행, 크기, 열 이름, dtype을 확인했던 방법을 떠올려보세요.

</details>

### Mission 1 Evidence

- 상품 수: ______개
- 열 수: ______개
- 가격 열의 dtype: ______
- 평점 열의 dtype: ______

# Mission 2 — 필요한 정보만 골라보기

In [26]:
# product 열만 선택하세요.
pass
print(products.columns)
products['product']

Index(['product', 'category', 'price', 'stock', 'rating'], dtype='str')

0       무선 마우스
1      기계식 키보드
2       USB 허브
3     블루투스 스피커
4           노트
5          플래너
6       형광펜 세트
7          텀블러
8       데스크 램프
9          정리함
10         티셔츠
11          후드
12         토트백
Name: product, dtype: str

In [28]:
# product와 price 열을 함께 선택하세요.
pass
products[['product','price']]

     product  price
0     무선 마우스  28000
1    기계식 키보드  89000
2     USB 허브  35000
3   블루투스 스피커  52000
4         노트   4500
5        플래너  12000
6     형광펜 세트   6500
7        텀블러  22000
8     데스크 램프  39000
9        정리함  19000
10       티셔츠  29000
11        후드  69000
12       토트백  32000

In [221]:
# product 한 열을 선택한 결과의 type을 확인하세요.
pass
print(type(products['product']))
print(type(products[['product']])

_IncompleteInputError: incomplete input (1647990881.py, line 4)

### 확인

한 열을 선택한 결과는 보통 무엇인가요?

- [ ] DataFrame
- [ ] Series

# Mission 3 — 데이터의 일부 위치만 보기

In [ ]:
# 첫 번째 상품의 전체 정보를 loc으로 확인하세요.
pass
products.loc[0] # 첫행(줄)

product     무선 마우스
category      전자기기
price        28000
stock           18
rating         4.3
Name: 0, dtype: object

In [ ]:
# 처음 3개 상품에서 product와 price 열만 loc으로 선택하세요.
pass
products.loc[0:2, ['product', 'price']] #loc[] 행의 슬라이스는 해당 인덱스 번호 의미

   product  price
0   무선 마우스  28000
1  기계식 키보드  89000
2   USB 허브  35000

In [ ]:
# iloc으로 첫 3행, 첫 2열을 선택하세요.
pass
products.iloc[0:3, 0:2] #iloc 슬라이스 숫자는 pd 프로그램 문법

   product category
0   무선 마우스     전자기기
1  기계식 키보드     전자기기
2   USB 허브     전자기기

<details>
<summary>힌트 보기</summary>

라벨 기준은 `loc`, 위치 기준은 `iloc`입니다.

</details>

# Mission 4 — 조건에 맞는 상품 찾기

완성된 코드를 떠올리기 전에, 어떤 열에 어떤 조건을 만들어야 하는지 먼저 생각하세요.

In [41]:
# 각 상품의 가격이 30,000원 이상인지 True/False로 확인하세요.
pass
products['price'] >= 30000

0     False
1      True
2      True
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11     True
12     True
Name: price, dtype: bool

결과는 왜 상품 수와 같은 개수의 True/False로 나왔나요?

In [227]:
# 가격이 30,000원 이상인 상품만 선택하세요.
pass
products['price']>=30000
print( products[products['price']>=30000] )
print( "총 행수", (products['price']>=30000).sum() )

     product category  price  stock  rating  low_stock
1    기계식 키보드     전자기기  89000      7     4.7       True
2     USB 허브     전자기기  35000     15     4.1      False
3   블루투스 스피커     전자기기  52000      9     4.5       True
8     데스크 램프       생활  39000     10     4.2       True
11        후드       패션  69000      6     4.8       True
12       토트백       패션  32000     16     4.1      False
총 행수 6

In [239]:
# 평점이 4.5 이상인 상품만 찾으세요.
pass
print(products[products['rating']>=4.5])
products[products['rating']>=4.5].iloc[:,0]

     product category  price  stock  rating  low_stock
1    기계식 키보드     전자기기  89000      7     4.7       True
3   블루투스 스피커     전자기기  52000      9     4.5       True
4         노트       문구   4500     42     4.5      False
7        텀블러       생활  22000     12     4.6      False
11        후드       패션  69000      6     4.8       True

1      기계식 키보드
3     블루투스 스피커
4           노트
7          텀블러
11          후드
Name: product, dtype: str

In [242]:
# 평점이 4.0 이상이면서 가격이 30,000원 이하인 상품을 찾으세요.
pass
df = products[(products['rating']>=4.0 ) & (products['price']>=30000)]
print(df)
df.iloc[:,0]

     product category  price  stock  rating  low_stock
1    기계식 키보드     전자기기  89000      7     4.7       True
2     USB 허브     전자기기  35000     15     4.1      False
3   블루투스 스피커     전자기기  52000      9     4.5       True
8     데스크 램프       생활  39000     10     4.2       True
11        후드       패션  69000      6     4.8       True
12       토트백       패션  32000     16     4.1      False

1      기계식 키보드
2       USB 허브
3     블루투스 스피커
8       데스크 램프
11          후드
12         토트백
Name: product, dtype: str

In [243]:
# 전자기기 또는 생활 카테고리 상품만 찾으세요.
pass
print(products.columns)
products[(products['category']=='전자기기') | (products['category']=='생활')]

Index(['product', 'category', 'price', 'stock', 'rating', 'low_stock'], dtype='str')

    product category  price  stock  rating  low_stock
0    무선 마우스     전자기기  28000     18     4.3      False
1   기계식 키보드     전자기기  89000      7     4.7       True
2    USB 허브     전자기기  35000     15     4.1      False
3  블루투스 스피커     전자기기  52000      9     4.5       True
7       텀블러       생활  22000     12     4.6      False
8    데스크 램프       생활  39000     10     4.2       True
9       정리함       생활  19000     20     3.9      False

<details>
<summary>힌트 보기</summary>

각 조건을 따로 만든 뒤, 동시에 만족하면 `&`, 둘 중 하나면 `|`로 연결합니다. 각 조건은 괄호로 묶으세요.

</details>

### Mission 4 Evidence

가격이 30,000원 이상인 상품은 ______개입니다.

그중 한 상품의 이름은 __________입니다.

# Mission 5 — 숫자를 계산해보기

In [52]:
# 상품의 평균 가격을 구하세요.
pass
print(products.columns)
products['price'].mean()

Index(['product', 'category', 'price', 'stock', 'rating'], dtype='str')

np.float64(33615.38461538462)

In [53]:
# 가장 높은 rating 값을 구하세요.
pass
products['rating'].max()

4.8

In [54]:
# 전체 재고 수량의 합을 구하세요.
pass
products['stock'].sum()

np.int64(227)

# Mission 6 — 새로운 정보 만들기

재고가 10개 이하인지 나타내는 `low_stock` 열을 만들어보세요.

In [ ]:
# stock이 10 이하인지 나타내는 low_stock 열을 만드세요.
pass
print(products.columns)
low_stock = products['stock'] <= 10
print(low_stock)
products['low_stock'] = low_stock
products

0     False
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11     True
12    False
Name: stock, dtype: bool

     product category  price  stock  rating  low_stock
0     무선 마우스     전자기기  28000     18     4.3      False
1    기계식 키보드     전자기기  89000      7     4.7       True
2     USB 허브     전자기기  35000     15     4.1      False
3   블루투스 스피커     전자기기  52000      9     4.5       True
4         노트       문구   4500     42     4.5      False
5        플래너       문구  12000     25     4.0      False
6     형광펜 세트       문구   6500     33     3.8      False
7        텀블러       생활  22000     12     4.6      False
8     데스크 램프       생활  39000     10     4.2       True
9        정리함       생활  19000     20     3.9      False
10       티셔츠       패션  29000     14     4.4      False
11        후드       패션  69000      6     4.8       True
12       토트백       패션  32000     16     4.1      False

In [ ]:
# low_stock 값별 상품 수를 확인하세요.
pass
print(products['low_stock'].value_counts())
print(products['low_stock'].sum()) # sum() 동작 방법: True의 결과행의 갯수 합 --> True --> 1 의 sum

low_stock
False    9
True     4
Name: count, dtype: int64
4

# Mission 7 — 가장 비싼 상품부터 보기

In [249]:
# 가격이 높은 상품부터 정렬하세요.
pass
products['price'].sort_values( ascending=False)

products.sort_values('price', ascending=False)

products.sort_values(['price'], ascending=False)

     product category  price  stock  rating  low_stock
1    기계식 키보드     전자기기  89000      7     4.7       True
11        후드       패션  69000      6     4.8       True
3   블루투스 스피커     전자기기  52000      9     4.5       True
8     데스크 램프       생활  39000     10     4.2       True
2     USB 허브     전자기기  35000     15     4.1      False
12       토트백       패션  32000     16     4.1      False
10       티셔츠       패션  29000     14     4.4      False
0     무선 마우스     전자기기  28000     18     4.3      False
7        텀블러       생활  22000     12     4.6      False
9        정리함       생활  19000     20     3.9      False
5        플래너       문구  12000     25     4.0      False
6     형광펜 세트       문구   6500     33     3.8      False
4         노트       문구   4500     42     4.5      False

In [250]:
# 가격이 가장 높은 상품 3개만 확인하세요.
pass
products.sort_values('price', ascending=False).head(3)

     product category  price  stock  rating  low_stock
1    기계식 키보드     전자기기  89000      7     4.7       True
11        후드       패션  69000      6     4.8       True
3   블루투스 스피커     전자기기  52000      9     4.5       True

<details>
<summary>힌트 보기</summary>

정렬 결과에서 처음 몇 행만 보는 두 작업을 조합해보세요.

</details>

# Mission 8 — 어떤 카테고리 상품이 가장 많을까요?

In [254]:
# category별 상품 수를 확인하세요.
pass

print(products['category'].value_counts() )

len(products) #행수의 갯수 합계

category
전자기기    4
문구      3
생활      3
패션      3
Name: count, dtype: int64

13

## 내가 찾은 결과

1. 상품은 총 ______개다.
2. 가격이 30,000원 이상인 상품은 ______개다.
3. 가장 비싼 상품은 __________이다.
4. 가장 높은 평점은 ______이다.
5. 상품 수가 가장 많은 카테고리는 __________이다.

In [183]:
print(products.columns , '\n')
products['product'].count()
print("1.상품은 총",products['product'].count(),"개다" )

products['price']>=30000
products.price[ products['price']>=30000 ].count()
print("2.가격이 30,000원 이상인 상품은", products.price[products['price']>=30000].count(), "개다.")

mask = products['price'] == products['price'].max()
prod =products[mask]['product'] 
price = products[mask]['price']
type(prod) #print(prod, price)
type(products[mask])
print(products[mask])
products[mask].loc[1,'product']
products[mask].loc[1,'price']
print("3.가장 비싼 상품은", products[mask].loc[1,'product'] , '가격은', products[mask].loc[1,'price'], "입니다")

products['rating'].max()
products['rating']==products['rating'].max()
mask2 = products['rating']==products['rating'].max()
print(products[mask2])
products[mask2].iloc[0,0]
print("4.가장 높은 평점은", products['rating'].max(), "상품이름은", products[mask2].iloc[0,0], "입니다." )

print(products['category'].value_counts())

print("5.상품 수가 가장 많은 카테고리는", "이다.")

Index(['product', 'category', 'price', 'stock', 'rating', 'low_stock'], dtype='str')

1.상품은 총 13 개다
2.가격이 30,000원 이상인 상품은 6 개다.
   product category  price  stock  rating  low_stock
1  기계식 키보드     전자기기  89000      7     4.7       True
3.가장 비싼 상품은 기계식 키보드 가격은 89000 입니다
   product category  price  stock  rating  low_stock
11      후드       패션  69000      6     4.8       True
4.가장 높은 평점은 4.8 상품이름은 후드 입니다.
category
전자기기    4
문구      3
생활      3
패션      3
Name: count, dtype: int64
5.상품 수가 가장 많은 카테고리는 이다.

# 스스로 점검하기

- 코드가 위에서 아래로 실행되나요?
- 결과가 질문에 실제로 답하나요?
- 꼭 필요한 데이터만 확인했나요?
- 같은 질문에 다른 코드로 답할 수도 있나요?

# Foundation Gate

이제 사용할 함수 이름을 알려주지 않습니다. 필요한 방법을 스스로 선택하세요.

### Gate 1

상품명, 가격, 평점만 선택하세요.

In [187]:
# 코드를 작성하세요.
pass
print(products.columns)
products[['product','price','rating']]

Index(['product', 'category', 'price', 'stock', 'rating', 'low_stock'], dtype='str')

     product  price  rating
0     무선 마우스  28000     4.3
1    기계식 키보드  89000     4.7
2     USB 허브  35000     4.1
3   블루투스 스피커  52000     4.5
4         노트   4500     4.5
5        플래너  12000     4.0
6     형광펜 세트   6500     3.8
7        텀블러  22000     4.6
8     데스크 램프  39000     4.2
9        정리함  19000     3.9
10       티셔츠  29000     4.4
11        후드  69000     4.8
12       토트백  32000     4.1

### Gate 2

가격이 20,000원 이상이고 평점이 4.3 이상인 상품을 찾으세요.

In [202]:
# 코드를 작성하세요.
pass

mask1 = (products['price']>= 20000) & (products['rating'] >= 4.3)
type(products[mask1])
print(products[mask1])
products[mask1].iloc[:,0]

     product category  price  stock  rating  low_stock
0     무선 마우스     전자기기  28000     18     4.3      False
1    기계식 키보드     전자기기  89000      7     4.7       True
3   블루투스 스피커     전자기기  52000      9     4.5       True
7        텀블러       생활  22000     12     4.6      False
10       티셔츠       패션  29000     14     4.4      False
11        후드       패션  69000      6     4.8       True

0       무선 마우스
1      기계식 키보드
3     블루투스 스피커
7          텀블러
10         티셔츠
11          후드
Name: product, dtype: str

### Gate 3

재고가 15개 이하인 상품을 가격이 높은 순서대로 정렬하세요.

In [212]:
# 코드를 작성하세요.
pass
products['stock'] <= 15
products[products['stock'] <= 15].sort_values('price', ascending=False)
products[products['stock'] <= 15].sort_values('price', ascending=False).loc[:,0]

KeyError: 0

### Gate 4

이 데이터에서 상품 구성에 관한 사실 하나를 찾으세요.

**내가 확인한 것:** ____________________________  
**근거가 된 숫자:** ____________________________  
**사용한 코드:** ______________________________

In [ ]:
# 탐색 코드를 작성하세요.
pass

<details>
<summary>힌트 보기</summary>

열 선택, 조건 선택, 정렬, 값의 개수, 평균·최댓값·최솟값 중 질문에 맞는 방법을 고르세요.

</details>

# Foundation Check

- [ ] 데이터 크기를 확인할 수 있다.
- [ ] 원하는 열을 선택할 수 있다.
- [ ] `loc`, `iloc`으로 일부 데이터를 선택할 수 있다.
- [ ] 조건을 True/False로 만들 수 있다.
- [ ] 조건에 맞는 행을 선택할 수 있다.
- [ ] 평균과 합계를 계산할 수 있다.
- [ ] 새로운 열을 만들 수 있다.
- [ ] 정렬하고 값별 개수를 확인할 수 있다.